### ISSUE TITLE
installing v1.1.0-RC is not successful

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit-electron#8]
I have centos 7 with gnome and I get error when trying to install the app.

[laurir@hp45 shared]$ ./dbvtk-gui-1.1.0.AppImage 
[25103:0807/090454.418821:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_dbvtk-hs1uoc/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
[laurir@hp45 shared]$ ls -l /tmp/.mount_dbvtk-qfbEeb/chrome-sandbox
ls: cannot access /tmp/.mount_dbvtk-qfbEeb/chrome-sandbox: No such file or directory
[laurir@hp45 shared]$

**Comment by 006627** [comment]
Hello Lauri

We are using the Electron API to create the AppImage, unfortunately, the recent version of Electron has this behavior in CentOS

A workaround to solve this problem would be to start the application with the parameter **--no-sandbox** as this [link](https://github.com/electron/electron/issues/17972#issuecomment-516957971) describes
```
./dbvtk-gui-1.1.0.AppImage --no-sandbox
```
We are building a new RC with a downgrade version of Electron API where the problem does not exist

**Comment by 006627** [comment]
https://github.com/keeps/db-visualization-toolkit-electron/releases/tag/v1.1.0-RC-2
